image_channels: 3
num_classes: 24
down_channels: [64, 128, 256, 512]
mid_channels: [512, 512, 512]
down_samples: [true, true, false]
emb_dim: 256
num_layers: 2
num_heads: 8
groups: 8
out_channels: 16
